@startuml

title UseCase

left to right direction

actor User
actor SafeWater

rectangle Software {

    usecase (Вхід у систему)
    usecase (Перегляд інформації щодо чистоти води неподалік)
    usecase (Спілкування з іншими користувачами щодо музики)
    usecase (Надання рекомендацій щодо збереження безпеки під час роботи)
    usecase (Отримання даних по запиту користувача)
    
    User -- (Вхід у систему)
    User -- (Перегляд інформації щодо чистоти води неподалік)
    User -- (Спілкування з іншими користувачами щодо музики)
    User -- (Надання рекомендацій щодо збереження безпеки під час роботи)
    User -- (Отримання даних по запиту користувача)

    (Вхід у систему) .> (Перегляд інформації щодо чистоти води неподалік) : include
    (Надання рекомендацій щодо збереження безпеки під час роботи) .> (Перегляд інформації щодо чистоти води неподалік) : include
    (Надання рекомендацій щодо збереження безпеки під час роботи) .> (Отримання даних по запиту користувача) : include

    SafeWater -- (Перегляд інформації щодо чистоти води неподалік) 
}

@enduml
